# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'smarthome' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#   pod 'react-native-ble-plx-swift', :path => '../node_modules/react-native-ble-plx'
  # Pods for smarthome

end
